### ISSUE TITLE
Recovery on bad json download

### ISSUE THREAD

**Issue by RapidfireCRH** [Thurion/EDSM-RSE-Database-Creator#1]
Automated script ran the database updater and it half downloaded the json file. Can we include some recovery into the program to delete the downloaded json if an error is encountered from the json decoder, then attempt to redownload the file?

```
Traceback (most recent call last):
  File "EDSM_RSE_Database_Creator.py", line 285, in <module>
    main()
  File "EDSM_RSE_Database_Creator.py", line 275, in main
    edsmRse.applyFilters()
  File "EDSM_RSE_Database_Creator.py", line 184, in applyFilters
    j = json.load(file)
  File "C:\Users\Rapid\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\Rapid\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Rapid\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Rapid\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 265381 column 6 (char 10419902
```)

Json ended at line 265381 with `    {"` which is why it errored

**Comment by Thurion** [comment]
The program will exist if it fails to download the file 3 times. The return code is 1 in that case.
